:trollface:
Inve1951/BetterDiscordStuff pull request #174
Opened 2022-08-02 02:27 UTC by AAGaming00

2022-08-02 03:03 UTC, AAGaming00 commented
this doesnt allow setting overrides, need to fix it

2022-08-02 03:33 UTC, AAGaming00 commented
Updated.

2022-08-02 11:38 UTC, Inve1951 commented
![](https://github.githubassets.com/images/icons/emoji/trollface.png)

2022-08-02 12:01 UTC, AsukeAZ commented
this doesn't work

2022-08-02 12:02 UTC, Inve1951 commented
it may have
discord is playing cat&mouse with breaking experiments for us right now

2022-08-02 12:03 UTC, AsukeAZ commented
yeah i don't know why they did that

2022-08-02 12:03 UTC, AsukeAZ commented
i was using a lot of features with the plugin now i can't sadly

2022-08-02 15:34 UTC, AAGaming00 commented
> it may have discord is playing cat&mouse with breaking experiments for us right now

Checked the diffs, they haven't patched this method yet.

2022-08-02 16:41 UTC, AAGaming00 commented
Should be fixed.

2022-08-02 16:52 UTC, ReeceDonovan commented
> Should be fixed.

![image](https://user-images.githubusercontent.com/42524740/182430528-8b7afd37-9550-48a0-9c99-b38214a40566.png)

2022-08-02 17:02 UTC, XxUnkn0wnxX commented
Tested it & it only allows you to view Experiments, not interact/change any of the experiments.

2022-08-02 17:08 UTC, AsukeAZ commented
thx u men

2022-08-02 17:10 UTC, XxUnkn0wnxX commented
yep all good here ;)

2022-08-02 23:31 UTC, DanielGolan-mc commented
when will this be merged? Can I use it before?

2022-08-02 23:36 UTC, DanielGolan-mc approved these changes
looks real to me.

2022-08-04 03:40 UTC, Inve1951 commented
I may merge it when discord stopped breaking it. No promises tho.

2022-08-05 09:45 UTC, XxUnkn0wnxX commented
for `actionHandler["CONNECTION_OPEN"]` please use "OVERLAY_INITIALIZE" since "CONNECTION_OPEN" has issues when trying to upload files or images in chat it fails..

I've tested it works with "OVERLAY_INITIALIZE"
Credits to **ace19#1790** for suggesting it..

2022-08-05 23:49 UTC, Tharki-God commented
experiment tab is not getting disabled when disabling the plugin

2022-08-06 14:48 UTC, D4rkov commented
> OVERLAY_INITIALIZE

type shall be changed to `"OVERLAY_INITIALIZE"` as well?

2022-08-06 16:01 UTC, D4rkov commented
The plugin stops working after some time, like you still have access to the experiments tab but you can't enable anything, and needs to be restarted.

2022-08-10 19:06 UTC, Orangenal-name commented
the branch is 2 commits behind

2022-08-11 07:29 UTC, D4rkov commented
@Inve1951 Just launched discord and I get this error.
![image](https://user-images.githubusercontent.com/83168801/184084634-2814fb03-3468-4f3f-aa78-d2ce9972889e.png)

2022-08-11 08:36 UTC, dav1312 requested changes

2022-08-11 08:36 UTC, dav1312 commented on plugins/discordexperiments.plugin.js
> +		const nodes = Object.values(settingsStore.default._dispatcher._dependencyGraph.nodes);
```js
const nodes = Object.values(settingsStore.default._dispatcher._actionHandlers._dependencyGraph.nodes);
```

2022-08-11 08:46 UTC, martijnmelchers commented
Anyone know why Discord is trying to make it harder to access experiments?

2022-08-11 09:00 UTC, Tharki-God commented
Because people are dumb

2022-08-11 15:12 UTC, closed without merging

2022-08-12 16:00 UTC, Tharki-God commented
okay , thanks for free promotion